export const API_BASE_URL = 'http://localhost:8080';
export const streetSuffixes = [
	'ABBEY',
	'ACRES',
	'ALLEY',
	'AVE',
	'BAY',
	'BEACH',
	'BEND',
	'BLVD',
	'BYPASS',
	'BYWAY',
	'CAMPUS',
	'CAPE',
	'CDS',
	'CHASE',
	'CIR',
	'CIRCT',
	'CLOSE',
	'COMMON',
	'CONC',
	'COVE',
	'CRES',
	'CRNRS',
	'CROSS',
	'CRT',
	'CTR',
	'DALE',
	'DELL',
	'DIVERS',
	'DOWNS',
	'DR',
	'END',
	'ESPL',
	'ESTATE',
	'EXPY',
	'EXTEN',
	'FARM',
	'FIELD',
	'FOREST',
	'FRONT',
	'FWY',
	'GATE',
	'GDNS',
	'GLADE',
	'GLEN',
	'GREEN',
	'GRNDS',
	'GROVE',
	'HARBR',
	'HEATH',
	'HGHLDS',
	'HILL',
	'HOLLOW',
	'HTS',
	'HWY',
	'INLET',
	'ISLAND',
	'KEY',
	'KNOLL',
	'LANDNG',
	'LANE',
	'LINE',
	'LINK',
	'LKOUT',
	'LMTS',
	'LOOP',
	'MALL',
	'MANOR',
	'MAZE',
	'MEADOW',
	'MEWS',
	'MOOR',
	'MOUNT',
	'MTN',
	'ORCH',
	'PARADE',
	'PASS',
	'PATH',
	'PINES',
	'PK',
	'PKY',
	'PL',
	'PLAT',
	'PLAZA',
	'PORT',
	'PROM',
	'PT',
	'PTWAY',
	'PVT',
	'QUAY',
	'RAMP',
	'RD',
	'RG',
	'RIDGE',
	'RISE',
	'ROW',
	'RTE',
	'RUN',
	'SQ',
	'ST',
	'SUBDIV',
	'TERR',
	'THICK',
	'TLINE',
	'TOWERS',
	'TRAIL',
	'TRNABT',
	'VALE',
	'VIA',
	'VIEW',
	'VILLAS',
	'VILLGE',
	'VISTA',
	'WALK',
	'WAY',
	'WHARF',
	'WOOD',
	'WYND',
];

export const provincesList = [
	{ name: 'Alberta', code: 'AB' },
	{ name: 'British Columbia', code: 'BC' },
	{ name: 'Manitoba', code: 'MB' },
	{ name: 'New Brunswick', code: 'NB' },
	{ name: 'Newfoundland and Labrador', code: 'NL' },
	{ name: 'Northwes Territories', code: 'NT' },
	{ name: 'Nova Scotia', code: 'NS' },
	{ name: 'Nunavut', code: 'NU' },
	{ name: 'Ontario', code: 'ON' },
	{ name: 'Prince Edward Island', code: 'PE' },
	{ name: 'Quebec', code: 'QC' },
	{ name: 'Saskatchewan', code: 'SK' },
	{ name: 'Yukon', code: 'YT' },
];

export const citiesList = [
	{
		province: 'AB',
		cities: [
			'Banff',
			'Brooks',
			'Calgary',
			'Edmonton',
			'Fort McMurray',
			'Grande Prairie',
			'Jasper',
			'Lake Louise',
			'Lethbridge',
			'Medicine Hat',
			'Red Deer',
			'Saint Albert',
		],
	},
	{
		province: 'BC',
		cities: [
			'Barkerville',
			'Burnaby',
			'Campbell River',
			'Chilliwack',
			'Courtenay',
			'Cranbrook',
			'Dawson Creek',
			'Delta',
			'Esquimalt',
			'Fort Saint James',
			'Fort Saint John',
			'Hope',
			'Kamloops',
			'Kelowna',
			'Kimberley',
			'Kitimat',
			'Langley',
			'Nanaimo',
			'Nelson',
			'New Westminster',
			'North Vancouver',
			'Oak Bay',
			'Penticton',
			'Powell River',
			'Prince George',
			'Prince Rupert',
			'Quesnel',
			'Revelstoke',
			'Rossland',
			'Trail',
			'Vancouver',
			'Vernon',
			'Victoria',
			'West Vancouver',
			'White Rock',
		],
	},
	{
		province: 'NU',
		cities: ['Iqaluit'],
	},
	{
		province: 'ON',
		cities: [
			'Bancroft',
			'Barrie',
			'Belleville',
			'Brampton',
			'Brantford',
			'Brockville',
			'Burlington',
			'Cambridge',
			'Chatham',
			'Chatham-Kent',
			'Cornwall',
			'Elliot Lake',
			'Etobicoke',
			'Fort Erie',
			'Fort Frances',
			'Gananoque',
			'Guelph',
			'Hamilton',
			'Iroquois Falls',
			'Kapuskasing',
			'Kawartha Lakes',
			'Kenora',
			'Kingston',
			'Kirkland Lake',
			'Kitchener',
			'Laurentian Hills',
			'London',
			'Midland',
			'Mississauga',
			'Moose Factory',
			'Moosonee',
			'Niagara Falls',
			'Niagara-on-the-Lake',
			'North Bay',
			'North York',
			'Oakville',
			'Orillia',
			'Oshawa',
			'Ottawa',
			'Parry Sound',
			'Perth',
			'Peterborough',
			'Picton',
			'Port Colborne',
			'Saint Catharines',
			'Saint Thomas',
			'Sarnia-Clearwater',
			'Sault Sainte Marie',
			'Scarborough',
			'Simcoe',
			'Stratford',
			'Sudbury',
			'Temiskaming Shores',
			'Thorold',
			'Thunder Bay',
			'Timmins',
			'Toronto',
			'Trenton',
			'Waterloo',
			'Welland',
			'West Nipissing',
			'Windsor',
			'Woodstock',
			'York',
		],
	},
	{
		province: 'MB',
		cities: [
			'Brandon',
			'Churchill',
			'Dauphin',
			'Flin Flon',
			'Kildonan',
			'Saint Boniface',
			'Swan River',
			'Thompson',
			'Winnipeg',
			'York Factory',
		],
	},
	{
		province: 'PE',
		cities: [
			'Borden',
			'Cavendish',
			'Charlottetown',
			'Souris',
			'Summerside',
		],
	},
	{
		province: 'SK',
		cities: [
			'Batoche',
			'Cumberland House',
			'Estevan',
			'Flin Flon',
			'Moose Jaw',
			'Prince Albert',
			'Regina',
			'Saskatoon',
			'Uranium City',
		],
	},
	{
		province: 'NB',
		cities: [
			'Bathurst',
			'Caraquet',
			'Dalhousie',
			'Fredericton',
			'Miramichi',
			'Moncton',
			'Saint John',
		],
	},
	{
		province: 'YT',
		cities: ['Dawson', 'Watson Lake', 'Whitehorse'],
	},
	{
		province: 'NL',
		cities: [
			'Argentia',
			'Bonavista',
			'Channel-Port aux Basques',
			'Corner Brook',
			'Ferryland',
			'Gander',
			'Grand Falls–Windsor',
			'Happy Valley–Goose Bay',
			'Harbour Grace',
			'Labrador City',
			'Placentia',
			'Saint Anthony',
			'St. John’s',
			'Wabana',
		],
	},
	{
		province: 'NT',
		cities: [
			'Fort Smith',
			'Hay River',
			'Inuvik',
			'Tuktoyaktuk',
			'Yellowknife',
		],
	},
	{
		province: 'NS',
		cities: [
			'Baddeck',
			'Digby',
			'Glace Bay',
			'Halifax',
			'Liverpool',
			'Louisbourg',
			'Lunenburg',
			'Pictou',
			'Port Hawkesbury',
			'Springhill',
			'Sydney',
			'Yarmouth',
		],
	},
	{
		province: 'QC',
		cities: [
			'Asbestos',
			'Baie-Comeau',
			'Beloeil',
			'Cap-de-la-Madeleine',
			'Chambly',
			'Charlesbourg',
			'Châteauguay',
			'Chibougamau',
			'Côte-Saint-Luc',
			'Dorval',
			'Gaspé',
			'Gatineau',
			'Granby',
			'Havre-Saint-Pierre',
			'Hull',
			'Jonquière',
			'Kuujjuaq',
			'La Salle',
			'La Tuque',
			'Lachine',
			'Laval',
			'Lévis',
			'Longueuil',
			'Magog',
			'Matane',
			'Montreal',
			'Montréal-Nord',
			'Percé',
			'Port-Cartier',
			'Quebec',
			'Rimouski',
			'Rouyn-Noranda',
			'Saguenay',
			'Saint-Eustache',
			'Saint-Hubert',
			'Sainte-Anne-de-Beaupré',
			'Sainte-Foy',
			'Sainte-Thérèse',
			'Sept-Îles',
			'Sherbrooke',
			'Sorel-Tracy',
			'Trois-Rivières',
			'Val-d’Or',
			'Waskaganish',
		],
	},
];

export const quandrants = ['NW', 'NE', 'SW', 'SE'];

export const colours = [
	'White',
	'Black',
	'Gray',
	'Silver',
	'Red',
	'Blue',
	'Brown',
	'Green',
	'Beige',
	'Orange',
	'Gold',
	'Yellow',
	'Purple',
];
